[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn 'test:app' --bind=0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30

[deploy.envs]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
