[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn test:app --log-level debug"
healthcheckPath = "/"
healthcheckTimeout = 60

[deploy.envs]
FLASK_APP = "test.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
