[build]
builder = "NIXPACKS"

[phases.setup]
cmds = ["python -m pip install --upgrade pip setuptools wheel"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[deploy]
startCommand = "gunicorn test:app --bind=0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30

[deploy.envs]
PYTHONUNBUFFERED = "1"
