[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn test:app --bind=0.0.0.0:$PORT --log-level debug"
healthcheckPath = "/"
healthcheckTimeout = 60

[deploy.envs]
FLASK_APP = "test.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
SERVER_NAME = "projet-bdd.railway.app"
