[build]
builder = "DOCKERFILE"
buildCommand = "docker build -t app ."

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.envs]
PORT = "8000"
