[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python test.py"
healthcheckPath = "/"
healthcheckTimeout = 30

[deploy.envs]
FLASK_APP = "test.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
PORT = "5000"
