[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn test:app"
healthcheckPath = "/"
healthcheckTimeout = 30

[deploy.envs]
FLASK_APP = "test.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
