[build]
builder = "NIXPACKS"

[deploy]
startCommand = "flask run --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30

[deploy.envs]
FLASK_APP = "test.py"
FLASK_ENV = "development"
PYTHONUNBUFFERED = "1"
