[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn wsgi:app --bind=0.0.0.0:$PORT --workers=4"
healthcheckPath = "/"
healthcheckTimeout = 60

[deploy.envs]
FLASK_APP = "wsgi.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
SERVER_NAME = "projet-bdd.railway.app"
SECRET_KEY = "your-secret-key-change-in-production"
