[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn test:app --bind=0.0.0.0:$PORT --timeout=120 --log-level=debug"
healthcheckPath = "/"
healthcheckTimeout = 120

[deploy.envs]
FLASK_APP = "test.py"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
